-- Alchemic Social Hub - SAFE BOOTSTRAP
-- Run this FIRST on the Clipper/Distributor Supabase.
-- It only adds missing compatibility columns + the metrics table.
-- Safe to re-run.

create extension if not exists pgcrypto;

alter table public.content_accounts add column if not exists display_name text;
alter table public.content_accounts add column if not exists token_type text default 'Bearer';
alter table public.content_accounts add column if not exists scope text;
alter table public.content_accounts add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.content_accounts add column if not exists error_message text;
alter table public.content_accounts add column if not exists capabilities_json jsonb not null default '{}'::jsonb;
alter table public.content_accounts add column if not exists webhook_status text not null default 'not_configured';
alter table public.content_accounts add column if not exists last_inbox_sync_at timestamptz;

create table if not exists public.post_metrics_snapshots (
  id bigint generated by default as identity primary key,
  history_id uuid not null references public.content_history(id) on delete cascade,
  captured_at timestamptz not null default now(),
  views bigint not null default 0,
  likes bigint not null default 0,
  comments bigint not null default 0,
  shares bigint not null default 0,
  saves bigint not null default 0,
  watch_time_seconds numeric,
  raw_json jsonb not null default '{}'::jsonb
);

create index if not exists post_metrics_snapshots_history_captured_idx
  on public.post_metrics_snapshots(history_id, captured_at desc);

update public.content_accounts
set capabilities_json =
  case
    when platform = 'instagram_reels' then coalesce(capabilities_json,'{}'::jsonb) || '{"publish":true}'::jsonb
    when platform = 'youtube_shorts' then coalesce(capabilities_json,'{}'::jsonb) || '{"publish":true,"analytics":true}'::jsonb
    else coalesce(capabilities_json,'{}'::jsonb)
  end;

-- Verification
select
  id,
  platform,
  username,
  capabilities_json,
  webhook_status
from public.content_accounts
order by created_at desc
limit 20;
