-- ============================================================
-- ALCHEMIC MEDIA V3 — DAILY PERFORMANCE + CONTENT ATTRIBUTION
-- Run once on the Media / Clipper Supabase project.
-- Safe to re-run.
-- ============================================================

create table if not exists public.post_daily_metrics (
  id bigint generated by default as identity primary key,
  workspace_id uuid references public.media_workspaces(id) on delete cascade,
  history_id uuid not null,
  metric_date date not null,
  source text not null default 'platform_api',
  platform text,
  views bigint not null default 0,
  likes bigint not null default 0,
  comments bigint not null default 0,
  shares bigint not null default 0,
  saves bigint not null default 0,
  watch_time_minutes numeric,
  average_view_duration_seconds numeric,
  raw_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(history_id, metric_date, source)
);

create index if not exists post_daily_metrics_workspace_date_idx
  on public.post_daily_metrics(workspace_id, metric_date desc);

create index if not exists post_daily_metrics_history_date_idx
  on public.post_daily_metrics(history_id, metric_date desc);

alter table public.post_daily_metrics enable row level security;

revoke all on table public.post_daily_metrics from anon, authenticated;
grant select, insert, update, delete on table public.post_daily_metrics to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Backfill workspace ownership from the corresponding published history row.
update public.post_daily_metrics d
set workspace_id = h.workspace_id
from public.content_history h
where d.history_id = h.id
  and d.workspace_id is null
  and h.workspace_id is not null;

select
  count(*) as daily_metric_rows,
  count(distinct history_id) as videos_with_daily_metrics
from public.post_daily_metrics;
